#image: maven:3-jdk-8

#stages:
#  - build
  
#maven-build:
#  stage: build
#  script: "mvn package"
#  artifacts:
#    paths:
#      - target/surefire-reports/TEST-*.xml
#    reports:
#      junit:
#        - target/surefire-reports/TEST-*.xml

image: maven:latest

stages: 
  - build
  - test
  - run

variables: 
  #MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository" 

cache: 
  paths: 
    - .m2/repository/ 
    - target/ 

build: 
  stage: build
  script: 
    - mvn $MAVEN_CLI_OPTS compile 

test: 
  stage: test 
  script: 
    - mvn $MAVEN_CLI_OPTS test 

run: 
  stage: run
  script: 
    - mvn $MAVEN_CLI_OPTS package 
    - mvn $MAVEN_CLI_OPTS exec:java -Dexec.mainClass="com.example.app.App"
