package model;

public enum Type {
    EMPTY, HILL, WATER, TOWER1,TOWER2, CASTLE, PLAYER1_CASTLE,PLAYER2_CASTLE, SOLDER1, SOLDER2,PLAYER1_SOLDIER1,PLAYER1_SOLDIER2,
    PLAYER2_SOLDIER1,PLAYER2_SOLDIER2,PLAYER1_TOWER1,PLAYER1_TOWER2,PLAYER2_TOWER1,PLAYER2_TOWER2, PLAYER1_TrainingField, PLAYER2_TrainingField
}
